name: Frontend Successfully Builds

on: [ pull_request ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v3
        with:
          # make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: build
        run: cd frontend && npm ci && npm run build